# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 18:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20171104_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='customer name', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.RemoveField(
            model_name='dish',
            name='order',
        ),
        migrations.AddField(
            model_name='dish',
            name='order',
            field=models.ManyToManyField(to='order.Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
