# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(default=b'name', max_length=50)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=50, null=True)),
                ('total_persons', models.CharField(max_length=4)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
