# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('book_a_table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetail',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='bookdetail',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookdetail',
            name='customer',
            field=models.CharField(max_length=50),
        ),
    ]
