# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-15 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_a_table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetail',
            name='customer',
            field=models.CharField(default='name', max_length=50),
        ),
    ]
