# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_a_table', '0002_auto_20171113_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetail',
            name='total_persons',
            field=models.CharField(max_length=4),
        ),
    ]
