# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_a_table', '0003_auto_20171113_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetail',
            name='contact',
            field=models.IntegerField(max_length=15),
        ),
    ]
