# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='customer',
        ),
    ]
