# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submenu',
            name='price',
            field=models.IntegerField(),
        ),
    ]
