# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-11 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menu_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
